# Append to VPATH
VPATH := $(VPATH):$(TOP)/solvers/poisson

# Dependencies
poisson_mod.o           : io_mod.o trace_mod.o mpi_mod.o kinds_mod.o patch_mod.o mesh_mod.o bits_mod.o scaling_mod.o omp_timer_mod.o
