# Vpath
VPATH := $(VPATH):$(TOP)/solvers/$(SOLVER):$(TOP)/solvers

# Dependencies
solver_mod.o            : io_mod.o trace_mod.o patch_mod.o extras_mod.o
initial_mod.o           : io_mod.o trace_mod.o patch_mod.o index_mod.o
