#!/bin/csh
#
# This file is intended to serve as "offline" version of `bitbucket-pipelines.yml`.
# Therefore, be sure to update it if `bitbucket-pipelines.yml` changes.
#
set wd = $cwd

ulimit -s 16384
setenv OMP_STACKSIZE 265m; setenv OMP_NUM_THREADS 1
echo "Run simple tests"
cd $wd; utilities/scripts/validate -x tests/meshes
cd $wd; cd tests/meshes; make clean; make; ./test.x
echo "Check compilation of experiments in validate_list.txt"
cd $wd; utilities/scripts/validate -l -v
echo "Everything is awesome!"
